/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        tertiary: "var(--color-tertiary)",
        "surface-variant": "#d8e3fa",
        "on-error-container": "#93000a",
        "tertiary-container": "#52595f",
        "surface": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#40484e",
        "on-tertiary-fixed": "#151c22",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002020",
        "tertiary-fixed": "#dce3eb",
        "surface-container-highest": "#d8e3fa",
        "inverse-primary": "#b0c6ff",
        "on-tertiary-container": "#c8cfd7",
        "primary-fixed": "#d9e2ff",
        "secondary-fixed": "#93f2f2",
        "primary-fixed-dim": "#b0c6ff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#006e6e",
        "primary-container": "#0f52ba",
        "on-secondary-fixed-variant": "#004f4f",
        "outline": "#737784",
        "surface-tint": "#1d59c1",
        "secondary-container": "#90efef",
        "inverse-surface": "#263142",
        "on-primary-fixed": "#001945",
        "on-primary-fixed-variant": "#00419c",
        "surface-dim": "#cfdaf1",
        "surface-container": "#e7eeff",
        "surface-container-low": "#f0f3ff",
        "secondary-fixed-dim": "#76d6d5",
        "error": "#ba1a1a",
        "on-primary-container": "#bcceff",
        "outline-variant": "#c3c6d5",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "on-background": "#111c2c",
        "background": "#f9f9ff",
        "surface-container-high": "#dee8ff",
        "on-primary": "#ffffff",
        "on-surface": "#111c2c",
        "tertiary-fixed-dim": "#c0c7cf",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#434653",
        "surface-bright": "#f9f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "margin": "32px",
        "unit": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ['Public Sans', 'sans-serif'],
        serif: ['Manrope', 'serif'],
        "headline-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "headline-xl": ["Manrope"],
        "body-lg": ["Public Sans"],
        "body-sm": ["Public Sans"],
        "label-md": ["Public Sans"],
        "body-md": ["Public Sans"],
        "label-sm": ["Public Sans"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
